### ISSUE TITLE
Resolve missing cross reference in documentation

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datapackr#1]
Lines 30-31 of unPackData.R makes reference to a function which cannot be found. 

#   \item Extracts MER data for use by the \code{\link{packSiteTool}}
#    function.

**Comment by jacksonsj** [comment]
Yeah, have yet to write that function... I can remove the link reference for now, just didn't want to forget about it later

**Comment by jason-p-pickering** [comment]
Not seeing this in the package checks any longer
