### ISSUE TITLE
Site Tool: Add code to remove tab if no data present

### ISSUE THREAD

**Issue by jacksonsj** [pepfar-datim/datapackr#13]
If no targets come from Data Pack for an entire tab, remove it to:

1. Save file space.
2. Prevent addition of targets in Site Tool outside of what was set in Data Pack.

**Comment by jacksonsj** [comment]
Should same logic apply to columns with all NA? If no target in Data Pack for an indicator, users shouldn't be allowed to set targets there in Site Tool either.

Downside to both these changes: If catastrophes occur where users have to start over from Data Pack and need to add data into previously unused indicators, they would need a brand new Site Tool, instead of having the option of manual re-alignment.

**Comment by jason-p-pickering** [comment]
Closing all old COP19 related tickets OBE.
