### ISSUE TITLE
Fix buggy code in createKeychainInfo

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datapackr#235]
Lines 98-103 in createKeyChainInfo seem to want to compare the names of sheets from the schema, to the names of the sheets contained in the DataPack to be parsed. 

1) This does not do what I think the authors intention was

```
any(tab_names_expected != tab_names_received)
```

If any tabs have been added, and the lengths are different, this warning will appear, since the vectors are of different lengths. 

```
Warning in tab_names_expected != tab_names_received :                                  
  longer object length is not a multiple of shorter object length
```

2) Pretty sure this is already taken care of in `checkStructure` anyway. 

@jacksonsj could you have a look and fix/remove?

**Comment by jacksonsj** [comment]
Added code that comments this out for now. Will improve the original test later when there's bandwidth.
