### ISSUE TITLE
getMechMap doesn't return the column name

### ISSUE THREAD

**Issue by sam-bao** [pepfar-datim/datapackr#34]
@jacksonsj I am getting an error when trying to pack a site tool that I have traced to this point.

https://github.com/pepfar-datim/datapackr/blob/600d4a8c48ff4d4ae513f0d2ce5dd8132ab2dc3a/R/packSiteTool.R#L405

It appears that get MechList is not returning a column named _name_ as expected at the referenced point in the code (and mabe some future points e.g. `x = data.frame(mechID = mechList$name)`). I get these columns when calling getMechList directly
```
> names(mechList)
[1] "mechanism" "code"      "uid"       "partner"   "primeid"   "agency"    "ou"        "startdate"
[9] "enddate"
```

I don't feel I know the code well enough here to fix this bug. Perhaps we should be using _mechanism_ instead of _name_ or perhaps we need to rename what is returned from getMechList.

**Comment by jacksonsj** [comment]
resolved in https://github.com/pepfar-datim/datapackr/pull/35
