### ISSUE TITLE
Error when packing site tool related to home tab

### ISSUE THREAD

**Issue by sam-bao** [pepfar-datim/datapackr#38]
```
 > datapackr::packSiteTool(d,
+                         output_path = paste0(support_dir_path, "site_tools/"))
Error in if (!stringr::str_detect(names(wb), "Home")) { : 
  argument is of length zero
> 
```

Seems to happen here, perhaps wb has no names at this point.

https://github.com/pepfar-datim/datapackr/blob/a99ed9d9ceb02b32b63caf0bd38a221c422c041c/R/packFrame.R#L21

**Comment by sam-bao** [comment]
https://github.com/pepfar-datim/datapackr/pull/39

**Comment by jason-p-pickering** [comment]
Closing all old COP19 related tickets OBE.
