### ISSUE TITLE
Add check for row 5 to colStructure checks

### ISSUE THREAD

**Issue by jacksonsj** [pepfar-datim/datapackr#46]
To detect cases where users have added rows above row 5 that causes problems, or where row 6 is not the beginning of data.

https://github.com/pepfar-datim/datapackr/blob/5c70538d636a74123f80279571af8986c23e69e3/R/checkColStructure.R#L33-L38

**Comment by jason-p-pickering** [comment]
Closing all old COP19 related tickets OBE.
