### ISSUE TITLE
Bug/BadError message in unpack site tool data

### ISSUE THREAD

**Issue by sam-bao** [pepfar-datim/datapackr#47]
https://github.com/pepfar-datim/datapackr/blob/0a19c126fecdb263f1b43b0e6cd9547df4206906/R/parseSiteTool.R#L427

While validating a South Africa site tool the validation app states:
![image](https://user-images.githubusercontent.com/36417685/57679932-c529cb80-762c-11e9-89a5-4e8b739ded0a.png)

Running the code from the terminal states: Error in if (any(has_positive_dedupe)) { :                                                           
  missing value where TRUE/FALSE needed

I determined there were rows in the PrEP tab of the site tool with blanks for the mechanism code (the very last rows of the table to be exact.) Once these cells were populated the validation worked.

**Comment by jason-p-pickering** [comment]
Closing all old COP19 related tickets OBE.
