### ISSUE TITLE
Trying datapackr, not working

### ISSUE THREAD

**Issue by HosseiniPR** [pepfar-datim/datapackr#6]
Scott et al.,

I ran this, after what seemed a successful install, and a restart (so I didn't have the whole history of the install), and I it dropped me out early with an error. 
```R

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(devtools)
Loading required package: devtools
> require(datapackr)
Loading required package: datapackr
> d <- unPackData()
[1] "Checking the file exists..."
[1] "Checking the OU name and UID on HOME tab..."
Error: expected <

```

Here is link to latest datapack which I was trying to check:
https://www.pepfar.net/ou/vietnam/HQ%20Collaboration/COP%202019%20%E2%80%93%20FY%202020/Original%20Submission%20of%20Required%20Tools%20(Feb%2021)/DataPack_Vietnam%2020190225%2018h00.xlsb

**Comment by jacksonsj** [comment]
Be sure to save as XLSX. Ironic, I know, considering we are the ones who produced the XLSBs, but the package can't read XLSBs. Just resave as XLSX and try again.

**Comment by jason-p-pickering** [comment]
Closing this as we cannot support the processing of XLSB at this point.
