### ISSUE TITLE
Year 2 sheet bug on check

### ISSUE THREAD

**Issue by achafetz** [pepfar-datim/datapackr#629]
Running `datapackr` (master) I run into a bug with the newly introduced `Year 2` tab. The tab does not does not match the structure of the other tabs (no PSNU information) which results in an error mapping through the data import. Not sure if this is part of your PR @jason-p-pickering in the `parse-year2` branch.

![image](https://user-images.githubusercontent.com/8933069/222452169-8bdc3daf-366f-4b20-b4c1-e22e4576f321.png)

**Comment by jason-p-pickering** [comment]
yeah..none of the this is ready yet.

**Comment by jason-p-pickering** [comment]
This should be fixed now in the latest version (6.2.0) @achafetz
