### ISSUE TITLE
False Positives for decimal values in unPackSheet

### ISSUE THREAD

**Issue by sam-bao** [pepfar-datim/datapackr#64]
This line of code is not reliably detecting non-integers.

https://github.com/pepfar-datim/datapackr/blob/9b34ce5775f503a1a6250a148b17a6a2da4f232e/R/unPackSheet.R#L133

As an example for this data pack: https://www.pepfar.net/Project-Pages/collab-38/Shared%20Documents/Data%20Pack%202019%20Staging%20Area/Support%20Files/datapacks/71_DataPack_Uganda_20190124160453_03082019.xlsx,

non decimals are flagged on the PMTCT_STAT_ART tab in the `PMTCT_STAT.D.Age/Sex.20T` column. However looking at the excel version of the data pack does not reveal any non-integer numbers. There appears to be some floating point error introduced when  readxl::read_excel initially reads in the sheet.

![image](https://user-images.githubusercontent.com/36417685/68291405-1c63a280-008a-11ea-9019-f021aabf5182.png)

**Comment by jason-p-pickering** [comment]
@sam-bao Is this still an issue? I think it has been solved in #65?
