### ISSUE TITLE
Bug in imbalancedDistribution Test

### ISSUE THREAD

**Issue by sam-bao** [pepfar-datim/datapackr#69]
with this data pack: https://www.pepfar.net/Project-Pages/collab-38/Shared%20Documents/Data%20Pack%202019%20Staging%20Area/Support%20Files/datapacks/DataPack_Malawi_03182019.xlsx

I am getting erroneous imbalanced distribution warnings:

```
13 :  WARNING!: 131 cases where distributed total is either more or less than total Target. To identify these, go to your SNU x IM tab and filter the Rollup column for Pink cells. This has affected the following indicators -> 
	* GEND_GBV.N.ViolenceServiceType.20T.physEmot
	* GEND_GBV.N.ViolenceServiceType.20T.postRape
	* HTS_INDEX_COM.N.Age/Sex/Result.20T.NewNeg
	* HTS_INDEX_COM.N.Age/Sex/Result.20T.NewPos
	* HTS_INDEX_FAC.N.Age/Sex/Result.20T.NewPos
	* HTS_SELF.N.Age/Sex/HIVSelfTest.20T.Directly_Assisted
	* HTS_SELF.N.HIVSelfTest.20T.Unassisted
	* HTS_TST_OtherMod.N.Age/Sex/Result.20T.Negative
	* HTS_TST_OtherPITC.N.Age/Sex/Result.20T.Positive
	* HTS_TST.N.KeyPop/Result.20T.Negative
	* HTS_TST.N.KeyPop/Result.20T.Positive
	* KP_PREV.N.KeyPop.20T
	* PrEP_CURR.N.Age/Sex.20T
	* PrEP_CURR.N.KeyPop.20T
	* PrEP_NEW.N.Age/Sex.20T
	* PrEP_NEW.N.KeyPop.20T
	* TB_ART.N.Age/Sex/NewExistingART/HIVStatus.20T.Already
	* TB_ART.N.Age/Sex/NewExistingART/HIVStatus.20T.New
	* TX_CURR.N.Age/Sex/HIVStatus.20T
	* TX_NEW.N.Age/Sex/HIVStatus.20T
	* TX_NEW.N.KeyPop/HIVStatus.20T
	* VMMC_CIRC.N.Age/Sex/HIVStatus.20T.Negative
	* VMMC_CIRC.N.Age/Sex/HIVStatus.20T.Positive
	* VMMC_CIRC.N.Age/Sex/HIVStatus.20T.Unknown
```

This screen shot has two rows from the same PSNU. NOTE that the value column has a different (exactly double) entry in the second row. 

![image](https://user-images.githubusercontent.com/36417685/68400292-13e99580-0178-11ea-84d3-c3dd8ee5e01c.png)

If we look at the data pack we see the targets are correctly allocated:

![image](https://user-images.githubusercontent.com/36417685/68400564-878ba280-0178-11ea-94bb-3d95a015f9dd.png)

![image](https://user-images.githubusercontent.com/36417685/68400833-f8cb5580-0178-11ea-90d2-9056cb5b53d5.png)

The affected code is here:

https://github.com/pepfar-datim/datapackr/blob/9b34ce5775f503a1a6250a148b17a6a2da4f232e/R/rePackSNUxIM.R#L92-L120

Seems like a problem in the group by/aggregation of the data.

**Comment by jason-p-pickering** [comment]
Was this ever fixed @jacksonsj ?

**Comment by sam-bao** [comment]
OBE
