### ISSUE TITLE
Remove use of "file.choose" if possible

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datapackr#7]
We will often need to automate these scripts, and having a user interaction required is problematic.Be sure to remove the use of `file.choose` if the required file path is not supplied as a parameter to the function which needs it.

**Comment by jacksonsj** [comment]
This change was made in both automation and siteTool branches. Merged from Automation -> master on 3/4. Will need to reconcile with similar change made in siteTool branch

**Comment by jason-p-pickering** [comment]
Should be resolved now , pending the merge of the **siteTool-merge** branch.
